services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: minishop
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  mountebank:
    image: bbyars/mountebank:latest
    ports:
      - "2525:2525"
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./mountebank.json:/app/mountebank.json
    command: start --configfile /app/mountebank.json --allowInjection